# -*- coding: utf-8 -*-
"""Cópia de Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_dbSJCQZEt0DbcegtjOVi-nYKJE1DMSU
"""

!pip install pyspark

from pyspark.sql import SparkSession
from pyspark.sql import functions as F

spark = SparkSession.builder\
    .master("local[*]")\
    .appName("spark_dataframe_api")\
    .getOrCreate()

df =(
    spark
    .read
    .option('delimiter', ';')
    .option('header', 'true')
    .option('inferSchema', 'true')
    .option('encoding', 'ISO-8859-1')
    .csv('/content/sample_data/precos-gasolina-etanol-10.csv')
)

df.show(5)

df.printSchema()

df_precos = (
    df
    .select('Estado - Sigla', 'Produto', 'Valor de Compra', 'Valor de Venda', 'Unidade de Medida')
)

df_precos.show(5)

(
    df_precos
    .where(
        F.col('Valor de Compra').isNotNull()
    )
    .show()
    )

from typing import cast

df_precos_cleaned = (
    df_precos
    .withColumn(
        "Valor de Venda_float",
        F.regexp_replace(F.col("Valor de Venda"), ",", ".").cast("float")
    )
    .withColumn(
        "Valor de Compra_float",
        F.regexp_replace(F.col("Valor de Compra"), ",", ".").cast("float")
    )
)
df_precos_cleaned.show(5)
df_precos_cleaned.printSchema()

df_precos_analise = (
    df_precos_cleaned # Use the cleaned DataFrame with float types
    .groupBy(
        F.col('Estado - Sigla'),
        F.col('Produto'),
        F.col('Unidade de Medida')
    )
    .agg(
        F.min(F.col("Valor de Venda_float")).alias('menor_valor'), # Use the float column
        F.max(F.col("Valor de Venda_float")).alias('maior_valor')  # Use the float column
    )
    .withColumn(
        "diferenca",
        F.col('maior_valor') - F.col('menor_valor')
        )
        .orderBy('diferenca', ascending=False)
    )

df_precos_analise.show(10)